Urban Nature Access: rename `greenspace` to `urban_nature`
natcap/invest pull request #1181
Opened 2023-02-12 00:00 UTC by phargogh

This PR renames everything in UNA to urban nature.

Fixes #1179

2023-02-15 22:07 UTC, dcdenu4 commented
Hey @phargogh, I likely created some merge conflicts from approving PR #1178

2023-02-15 22:14 UTC, dcdenu4 requested changes
Just requesting changes for the conflict merges, so I can be pinged to re-review.

2023-02-15 22:46 UTC, phargogh commented
Uffda, that was quite the merge conflict! I just pushed an update @dcdenu4 and am just waiting on the tests to pass.

2023-02-21 14:33 UTC, dcdenu4 approved these changes

2023-02-21 14:33 UTC, merged