Removing the ws_id field requirement in SDR.
natcap/invest pull request #1204
Opened 2023-02-27 19:41 UTC by phargogh

This field is a relic from earlier versions of the model where we provided an optional valuation step that associated valuation parameters with the watersheds via the WS_ID field.  We removed the valuation component, but forgot to remove the required WS_ID field.

Fixes #1201 

@newtpatrol I've added you as an assignee here as an FYI ... you're of course welcome to review the changes here if you like, up to you!

## Checklist
- [x] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the affected models' UIs (if relevant)

2023-02-27 20:46 UTC, newtpatrol commented
That was fast @phargogh, thanks!

2023-02-27 21:16 UTC, emlys requested changes
@phargogh just one small issue breaking the tests!

2023-02-27 21:20 UTC, phargogh commented on src/natcap/invest/sdr/sdr.py
> -            },
Yep, that was it!  I just patched this and pushed the fix.

2023-02-28 00:31 UTC, emlys approved these changes
Looks good, failing tests are unrelated

2023-02-28 00:31 UTC, merged