Update License and add new TM InVEST logo
natcap/invest pull request #1385
Opened 2023-08-25 20:09 UTC by dcdenu4

## Description
Update the License from 3-Clause BSD to Apache 2.0 and add a NOTICE companion file. The custom copyright is now moved into the NOTICE file.

Update the InVEST logos to use the new registered TM logos. Add a registered TM symbol to InVEST in the Workbench.

Fixes #795 
Fixes #1287 
Fixes #1148 

## Checklist
- [ ] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the Workbench UI (if relevant)

2023-08-29 14:19 UTC, davemfish requested changes
I tried this on Windows, looks great!

I wonder if you want to also distribute the new NOTICE alongside the LICENSE? Also, while we're here do you think it makes sense to move the location of our `LICENSE.txt` in the application's install directory?

Now it's at,
`<root install>/resources/LICENSE.InVEST.txt`,

whereas some other licenses are at,
`<root install>/LICENSE.electron.txt`
`<root install>/LICENSES.chromium.html`

If we wanted to move ours alongside theirs, I think we just put it in `extraFiles` as opposed to `extraResources` in `electron-builder-config.js`.

2023-08-29 14:19 UTC, davemfish commented on workbench/resources/InVEST-2-256x256.ico
These ico files were just replaced with new ones right? `electron-builder-config.js` doesn't have any changes so presumably still points to these.

2023-08-29 15:09 UTC, dcdenu4 commented on workbench/resources/InVEST-2-256x256.ico
Yep, I just wrote over the existing ones. I thought about creating new filenames to be explicit, but didn't ultimately see the big benefit.

2023-08-29 19:28 UTC, dcdenu4 commented on doc/decision-records/ADR-0002-Switch-InVEST-License.md
> +- PR Draft
Good point, done in https://github.com/natcap/invest/pull/1385/commits/800b91cb239881f52036dbc24369a36bcef6a034

2023-08-29 19:30 UTC, dcdenu4 commented on workbench/src/renderer/menubar/about.jsx
> +                    href="https://github.com/natcap/invest/blob/master/LICENSE.txt"
Good catch. Done in https://github.com/natcap/invest/pull/1385/commits/3785889eff56c979787ea80c5b6e2f1fd2a3152c

2023-08-29 19:42 UTC, dcdenu4 commented on workbench/src/renderer/styles/style.css
> +  margin-bottom: 0.3rem;
Okay, I think I replaced everything with 2 spaces... hopefully this is helpful!

2023-08-29 19:43 UTC, dcdenu4 commented
Thanks @davemfish, I think I covered everything. Bumped the distribution location of the License up one and added the Notice file.

Let me know if I helped or made more a mess with the style css indenting!

2023-08-29 20:01 UTC, dcdenu4 commented
@davemfish and @phargogh I snuck in an update to HISTORY that removes the 3.14.0 header and puts its contents in the proper spot below. This is to avoid conflict with how the auto release script updates HISTORY.

2023-08-29 21:06 UTC, davemfish requested changes
Thanks @dcdenu4 , just a syntax error in the electron builder config.

2023-08-29 21:06 UTC, davemfish commented on workbench/electron-builder-config.js
> +  ]
missing comma here

2023-08-29 22:55 UTC, phargogh requested changes
Just one small change and a question about the status, but it looks great otherwise!  I tried out the mac build of the workbench and all of the updates were looking really good.

2023-08-30 17:41 UTC, dcdenu4 commented on workbench/electron-builder-config.js
> +  ]
Good eye! https://github.com/natcap/invest/pull/1385/commits/0d5adc586a10e4fdf57259c6bdfff5c1eb844cbd

2023-08-30 17:44 UTC, dcdenu4 commented on doc/decision-records/ADR-0002-Switch-InVEST-License.md
> +Complete
Added to this noting the 3.14.0 release. I think generally the "Status" field is maybe only applicable when the ADR is created before and separate of the implementation. I almost think that "Status" or "Details" could live at the top of the ADR... things to think about and iterate on!

2023-08-30 17:55 UTC, phargogh approved these changes

2023-08-30 18:25 UTC, davemfish approved these changes

2023-08-30 18:25 UTC, merged