add a datastack arg to the export-py CLI command.
natcap/invest pull request #1473
Opened 2023-12-12 14:58 UTC by davemfish

`invest export-py routedem -d data\invest-sample-data\RouteDEM\routedem_gura.invs.json -f run_routedem.py`

Now populates the `args` dict in `run_routedem.py` with values from the given parameter set. 

We already have tests that assert the args are included in the script correctly. I added one to test the new command-line arg.

Fixes #1472 

## Checklist
- [x] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the Workbench UI (if relevant)

2023-12-12 19:33 UTC, emlys commented on tests/test_cli.py
> +        with redirect_stdout() as stdout_stream:
My understanding is this just prevents the stdout from showing up in the test output? If `stdout_stream` is not used, can this be simplified?
```suggestion
        with redirect_stdout():
```
```

2023-12-12 19:40 UTC, emlys requested changes
Thanks @davemfish! My only other comment is that it's a little redundant to have to provide the model name as an argument, when it's also known from the datastack. I see why that's necessary using the `export_py` subparser though. Another option would be to make a separate command for converting a datastack to a script - but that would be extra work for a pretty minor issue.

2023-12-13 14:43 UTC, davemfish commented
> Thanks @davemfish! My only other comment is that it's a little redundant to have to provide the model name as an argument, when it's also known from the datastack. I see why that's necessary using the `export_py` subparser though. Another option would be to make a separate command for converting a datastack to a script - but that would be extra work for a pretty minor issue.

Yeah that's a great point @emlys . Okay let's not be hasty and design this properly then. I'm going to put this PR in draft mode and we can discuss further in #1472

2024-02-13 14:22 UTC, davemfish commented
Closing this since I'm not working on it. We can always re-open if we work on #1472

2024-02-13 14:22 UTC, closed without merging