Distribute mamba with workbench
natcap/invest pull request #1604
Opened 2024-07-31 19:20 UTC by emlys

…n-builder

## Description
Fixes #

## Checklist
- [ ] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the Workbench UI (if relevant)

2024-09-09 16:23 UTC, dcdenu4 requested changes
Thanks @emlys and sorry for being so slow. I had a few comments and questions but nothing major.

You mentioned commenting out the puppeteer test, I don't see that in here. Was that testing pulled out of this PR or handled elsewhere?

2024-09-09 16:23 UTC, dcdenu4 commented on workbench/src/main/findBinaries.js
> +  // Binding to the invest server binary:
Copied comment?

2024-09-09 16:23 UTC, dcdenu4 commented on workbench/src/main/findBinaries.js
> +  const filename = `invest${ext}`;
It looks like these are leftover and not used.

2024-09-09 16:23 UTC, dcdenu4 commented on workbench/src/main/main.js
> +  settingsStore.set('mamba', findMambaExecutable(ELECTRON_DEV_MODE));
This is nitpicky but do we want to be consistent with whether we create a variable for a returned binary path or just call it from within the function signature?

2024-10-08 20:52 UTC, emlys commented
@dcdenu4 I fixed those small issues. I had found that the puppeteer test failure was not specific to this branch, but was also happening on `feature/plugins`, so I directly commented it out on that branch. So that change isn't in this PR.

2024-10-10 12:44 UTC, dcdenu4 approved these changes
Thanks @emlys , I think this is good to merge!

2024-10-10 12:44 UTC, merged