Raise Exception for NA Keys in reclassify_raster and test HQ missing lulc value
natcap/invest pull request #1703
Opened 2024-12-07 00:08 UTC by claire-simpson

## Description
Raises exception in `reclassify_raster` function in utils when `value_map` contains NA key. Provides a more specific error message.

New test checks that specific error is raised if LULC value is missing.

This fixes the issue in HQ where an ambiguous error message was raised due to missing LULC value in sensitivity table 

Fixes #1671

## Checklist
- [ ] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the Workbench UI (if relevant)

2024-12-09 14:43 UTC, davemfish requested changes
@claire-simpson this looks good to me, thanks! Would you mind adding a note to HISTORY, and reviewing a couple very minor comments I had. Thanks,

2024-12-09 16:09 UTC, claire-simpson commented
> Would you mind adding a note to HISTORY

In addition to noting better error handling related to missing LULC values in HQ, would a note more generally describing error handling when trying to reclassify NA values be helpful?

2024-12-09 17:51 UTC, davemfish commented
> @davemfish
> 
> > Would you mind adding a note to HISTORY
> 
> In addition to noting better error handling related to missing LULC values in HQ, would a note more generally describing error handling when trying to reclassify NA values be helpful?

Yeah, I think a general statement about raster reclassification makes sense.

2024-12-10 13:34 UTC, davemfish approved these changes

2024-12-10 13:34 UTC, merged