Convert per-pixel values to per-hectare values in raster outputs of multiple models
natcap/invest pull request #1717
Opened 2024-12-18 00:49 UTC by emilyanndavis

## Description
Fixes #1270. Specifically, the following models (and their tests) have been updated:
- [x] Carbon
- [x] SDR
- [x] NDR
- [x] Forest Carbon
- [x] Crop Production: Percentile
- [ ] Crop Production: Regression

Where these models previously produced raster outputs whose pixel values were in per-pixel units (e.g., Mg C/px, or kg N/(px•yr), etc.), they now produce raster outputs whose pixel values are in per-hectare units (e.g., Mg C/ha, or kg N/(ha•yr), etc.).

Regression tests now check raster outputs to make sure their values are in the appropriate units, and they also check any summary tables to make sure reported totals (e.g., total Mg C, or total kg N/yr, etc.) remain unchanged. 

(Also includes some cleanup of miscellaneous items, such as unused variables, PEP8 issues picked up by my linter, and typos I noticed while reading the code and/or the user guide.)

## Checklist
- [ ] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the Workbench UI (if relevant)

2025-02-07 17:26 UTC, davemfish requested changes
This looks great, @emilyanndavis. I appreciate the comments about unit conversions and using the same regression values when possible to confirm that the results are correct. I have just a few minor comments.

2025-02-10 22:39 UTC, emilyanndavis commented on src/natcap/invest/crop_production_regression.py
> -                  aggregate_results_table_path),
Good question. Looking back at this now, I'm sure I must have removed `aggregate_results_table_path` from the args because it wasn't being referenced by the `aggregate_regression_results_to_polygons` function. It is still included in the `target_path_list` that is passed to taskgraph, though, and the `target_path_list` does get logged (at least when taskgraph logging is set to debug). Would you say that's sufficient, or do you think I should add `aggregate_results_table_path` back to the args as well?

2025-02-11 00:08 UTC, emilyanndavis commented on tests/test_ndr.py
> +        pixels_per_hectare = 10000 / 900
Good idea, thanks!

2025-02-11 16:57 UTC, emilyanndavis commented on src/natcap/invest/crop_production_regression.py
> -                  aggregate_results_table_path),
I see, thanks. I'll make a few changes.

2025-02-12 13:24 UTC, dcdenu4 commented on src/natcap/invest/ndr/ndr.py
> -                        "eff_x, following an exponential decay.")},
Is this just being removed for general clean up or because it's duplicated in the User Guide?

2025-02-12 13:27 UTC, dcdenu4 commented on src/natcap/invest/sdr/sdr.py
> -def _calculate_d_up_bare(
Was this function not be called / used?

2025-02-12 17:03 UTC, emilyanndavis commented on src/natcap/invest/crop_production_regression.py
>      aggregate_table_path = os.path.join(
Yes, I also agree, and I just updated this!

2025-02-12 17:09 UTC, emilyanndavis commented on src/natcap/invest/ndr/ndr.py
> -                        "eff_x, following an exponential decay.")},
Sorry, I should have left a note about this. I removed this sentence because it is duplicated* in the User Guide.

*In fact, the UG version isn't an exact duplicate, since the UG version looks to have been revised to remove typos and improve clarity.

2025-02-12 17:25 UTC, emilyanndavis commented on HISTORY.rst
> +      <https://github.com/natcap/invest/issues/1270>`_).
It would be a little tedious, but I can add it if you think it would be helpful. Each list would likely have somewhere between 3 and 8-ish filenames, depending on the model. What do you think?

2025-02-13 14:50 UTC, davemfish approved these changes
Changes look good, thanks!

2025-02-14 13:47 UTC, dcdenu4 approved these changes
Thanks @emilyanndavis !

2025-02-14 13:47 UTC, merged