CV shore point interpolation memory error
natcap/invest pull request #370
Opened 2020-11-05 12:32 UTC by dcdenu4

This PR is a proposed solution for the memory error in `interpolate_shore_points`. The memory error occurs when very large intersecting landmasses are used. The `shapely.ops.linemerge()` call ends up busting memory on these very large landmass line geometries.

The proposed solution uses an arbitrary interval value that is used to "chunk" up how many line geometries make it to the `linemerge` function. In this implementation for each "chunk" shore points are interpolated on that set of lines and written to the vector output. This means that on quite large AOIs and Landmass vectors there will be a slight difference versus interpolating shore points on all of the line geometries. This difference is pretty minimal in reality and I think provides just as good a solution.

The interval value is an added optional parameter to the function.

I did include a test, that uses a very small interval value which gets a different number of shore points interpolated. I'm not sure if this "covers" this new parameter. 

Fixes #352

2020-11-05 17:25 UTC, davemfish requested changes
Hi @dcdenu4 , I have a few minor comments for you to consider. And then I had one larger concern after trying out the test and looking at it's outputs.

I think the test case does cover the new functionality. But there's something strange with point placement. There are two points in the same location, and a larger than expected gap in another location. That will probably be a very minor detail in the context of a "real-world" AOI, but I'd kinda like to understand it and address it. I think it could be a bigger deal if the landmass is very large & complicated (lots of line segments and many times exceeding the linemerge limit) but the model resolution is fairly coarse. Then duplicate points might skew an aggregated result. Or a larger gap could become very noticeable. And that's actually what the data in this test is like: 25m segments on the landmass polygon and a 100m model resolution.

I'd like to give this a little more thought and then maybe chat about it again?

2020-11-05 20:47 UTC, dcdenu4 commented
Hey @davemfish , sorry about this dumpster fire, good thing we have PRs! I got caught sleeping, programming by coincidence. I'll take a more detailed look over what's happening and your comments. Then we can chat!

2020-11-05 21:01 UTC, davemfish commented
> Hey @davemfish , sorry about this dumpster fire, good thing we have PRs! I got caught sleeping, programming by coincidence. I'll take a more detailed look over what's happening and your comments. Then we can chat!

That's not at all the message I was trying to send here! Your PR is exactly what we already discussed. I just hadn't realized until this late stage how I really felt about the solution. And probably couldn't have realized it without seeing it implemented and tested, so thank you for doing that! It's all part of the process. And I'm not even certain if we'll find a nicer solution without expanding the scope of the changes, which I think we're both hesitant to do. But I'll think on that too and then we can talk.

2020-11-06 19:57 UTC, dcdenu4 commented
@davemfish and I discussed the issues raised above and have decided on a path forward. Keeping this PR alive for the history but going to demote it to Draft.

2020-11-12 15:02 UTC, dcdenu4 commented
@davemfish okay, tests are passing! 

This PR is updated to combine the interpolation of shore points with the prepping of landmass geometries. The joining of these two processes into one allows for better use of memory management and resources so we don't have to duplicate operations.

2020-11-16 17:58 UTC, davemfish requested changes
Hey @dcdenu4 , I think this a huge improvement over the way we used to do this. I think this solution is great, there's just one step in the iterations that I think can be streamlined. See what you think there - about doing the rtree build & the aoi intersection check all in one loop. And some minor comments on the tests. Thanks!

2020-11-16 18:29 UTC, dcdenu4 commented on src/natcap/invest/coastal_vulnerability.py
> +        for shapely_landmass_line in shapely_line_index[line_id_previous:]:
You're totally right about this. Glad I made things more convoluted, would have been to easy to review, haha.

2020-11-16 18:30 UTC, dcdenu4 commented
@davemfish assuming the new tests pass on GHA I made the changes you suggested here: https://github.com/natcap/invest/pull/370/commits/e0fafc9bb35c393a00e8e91a7978223f77b06487.

2020-11-16 18:47 UTC, davemfish approved these changes
Sweet! All passed. Thanks for merging that test data PR too! @dcdenu4

2020-11-16 18:47 UTC, merged