Task/719 deprecate fish
natcap/invest pull request #748
Opened 2021-12-03 16:25 UTC by davemfish

# Description
Fixes #

# Checklist
- [ ] Updated HISTORY.rst (if these changes are user-facing)

- [ ] Updated the user's guide (if needed)

2021-12-03 20:25 UTC, emlys requested changes
Awesome @davemfish! Just had a tiny suggestion

2021-12-03 20:25 UTC, emlys commented on HISTORY.rst
> +* Fisheries
```suggestion
* Fisheries and Fisheries HST
```

2021-12-03 20:36 UTC, davemfish commented
@emlys done!

2021-12-03 21:46 UTC, emlys approved these changes
Hooray! So satisfying to see so much code deleted lol

2021-12-03 21:46 UTC, merged

2021-12-08 23:45 UTC, phargogh commented
Wow, I only just noticed just _how_ much code was removed here.  Let us pause for a melancholy moment in their memory.