Resolving merge conflict in HISTORY in #760
natcap/invest pull request #761
Opened 2021-12-10 23:34 UTC by phargogh

This is minor merge conflict resolution related to #760 in `HISTORY`.

2021-12-10 23:42 UTC, emlys requested changes
Just one suggestion to fix a typo!

2021-12-10 23:42 UTC, emlys commented on HISTORY.rst
> +    * Fixed bug where output vectors had coordinates with an unncessary
```suggestion
    * Fixed bug where output vectors had coordinates with an unnecessary
```

2021-12-11 00:58 UTC, phargogh commented
Whoops, thanks @emlys !  Guess I need to get my spellcheck back up and running.

2021-12-11 01:48 UTC, emlys approved these changes

2021-12-11 02:21 UTC, merged