Ensure kernels are tiled in HRA and GLOBIO
natcap/invest pull request #846
Opened 2022-02-03 23:35 UTC by phargogh

This PR tiles convolution kernels in Habitat Quality and GLOBIO that were not yet tiled.  This is done through setting some GDAL options and should produce no functional change on the sample data.  The only consequence of this improvement should be improved runtimes in convolutions (particularly with large kernels) and should also help avoid a case where a large-enough kernel would cause an underlying error in pygeoprocessing to be raised.

I left off automated tests for this because ensuring something is tiled feels like a GDAL-level issue and not something that InVEST should manage, but let me know if you object!

This PR is a stop-gap to mitigate this bug in response to a forums post (https://community.naturalcapitalproject.org/t/habitatquality-error-encountered-in-threats-table-threats-distribution-map/2476).  I think the real solution here is in #731  and will involve a redesign of how we work with convolution kernels.

Fixes #843 

## Checklist
- [x] Updated HISTORY.rst (if these changes are user-facing)
~~- [ ] Updated the user's guide (if needed)~~
~~- [ ] Tested the affected models' UIs (if relevant)~~

2022-02-04 14:07 UTC, dcdenu4 requested changes
Thanks for this patch @phargogh . I think I agree that this doesn't seem like something InVEST should be responsible for in testing.

I did have one comment on the setuptools version since a new Pyinstaller release has just come out that should fix that problem.

Thanks!

2022-02-04 16:42 UTC, phargogh commented
@dcdenu4 I just removed that setuptools restriction in favor of using the latest pyinstaller.  Back to you!

2022-02-04 16:43 UTC, phargogh commented on requirements-dev.txt
> +setuptools>=8.0,<60.7.0  # https://github.com/pyinstaller/pyinstaller/issues/6564
Sounds good to me!

2022-02-04 18:06 UTC, dcdenu4 commented
@phargogh looks like the latest Pyinstaller version was not selected, but 4.8 was used again.

2022-02-04 18:10 UTC, emlys commented
@dcdenu4 @phargogh it looks like pyinstaller 4.9 was out on PyPI early this morning, but was just released on conda-forge (like 1 minute ago). So rerunning yet again should work.

2022-02-04 18:14 UTC, phargogh commented
Thanks @emlys!  I just re-triggered the builds.

2022-02-04 18:32 UTC, emlys commented
Argh, I also retriggered builds on #841 and it's still not working. `conda install pyinstaller==4.9` also fails even though [the files are there](https://anaconda.org/conda-forge/pyinstaller/files). Maybe there's some index that takes a while to update?

2022-02-04 21:11 UTC, dcdenu4 commented
I didn't think about the time needed for a conda feedstock rollout.

2022-02-07 22:07 UTC, dcdenu4 reviewed
@phargogh , I've started re-running some tests to see if they'll pass. I think getting tests to pass / confirming they're not related to this PR is all that is left here.

2022-02-08 14:49 UTC, dcdenu4 commented
Looks like the build issue is now documented in #880 and not caused by this PR. I'll go ahead and merge this.

2022-02-08 14:49 UTC, merged