Incorporate invest-workbench into this repo
natcap/invest pull request #847
Opened 2022-02-04 18:58 UTC by davemfish

This PR adds all the workbench files into a `workbench` directory. It updates the invest GHA workflows to also test, build, and deploy the workbench. Changes on the workbench side (to remove now unnecessary scripts, etc) can also be reviewed in [this PR,](https://github.com/natcap/invest-workbench/pull/221) just to make it easier to review. 

So if you like, it's okay to only review files that are not in the `workbench` directory here.
Addresses #844 

## Checklist
- [ ] Updated HISTORY.rst (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the affected models' UIs (if relevant)

2022-02-11 00:50 UTC, emlys commented on requirements-dev.txt
> +setuptools>=8.0,<60.7.0 # https://github.com/pyinstaller/pyinstaller/issues/6564
Also from a different PR?

2022-02-11 00:52 UTC, emlys commented on .github/workflows/binary-applications.yml
> +            #       path: dist/InVEST-*-mac.zip
Yeah, this step can be deleted.

2022-02-11 13:10 UTC, dcdenu4 commented on Makefile
> +	BASHLIKE_SHELL_COMMAND := '$(SHELL)' -c
Nice, I also noticed this in something I'm working on

2022-02-11 13:19 UTC, dcdenu4 commented on Makefile
> +# 	-(cd $(INVEST_BINARIES_DIR) && $(ZIP) -r ../$(INVEST_BINARIES_DIR_ZIP) .)
Can this and the related commented out line above be removed?

2022-02-11 13:23 UTC, dcdenu4 requested changes
Hey @davemfish , this is looking good! Excited to pull these changes locally soon. Everything from this PR and the related draft PR over on the workbench repo make sense to me. As Emily noted there are a few things in here that were seemingly taken care of in past PRs.

2022-02-11 17:55 UTC, davemfish commented
@emlys & @dcdenu4 I pushed updates to remove those bits of commented code, and to merge in the latest `main`. So I think those things address all your comments.

I see that there is still a README in `workbench/internationalization`, but it does seem to have some unique content relative to the invest readme so I think I'll leave it as-is and we can remove redundancy later if there is some?

There was a leftover workbench script for code signing that I just removed too.

2022-02-14 23:39 UTC, phargogh approved these changes
Very exciting to see the two repos coming together!  I don't see anything that hasn't already been commented on.

2022-02-14 23:56 UTC, emlys approved these changes

2022-02-15 16:51 UTC, merged