Replace "upstream"/"downstream" with "upslope"/"downslope"
natcap/invest pull request #896
Opened 2022-03-01 23:53 UTC by emlys

## Description
@jagoldstein requested via Slack that we replace "upstream" and "downstream" with "upslope" and "downslope" in the documentation, because the terms apply whether or not a pixel is actually in a stream. I also replaced these throughout the code and comments since that distinction might be helpful when we're thinking about the algorithms.

## Checklist
- [ ] Updated HISTORY.rst (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the affected models' UIs (if relevant)

2022-03-02 00:03 UTC, jagoldstein commented
thanks @emlys ! To be clear, there may be a small handful of mentions of "downstream" that are correct in the UG. Here's an example from [SDR](http://releases.naturalcapitalproject.org/invest-userguide/latest/sdr.html#sediment-retention-services): "_This quantifies the difference in erosion reaching a stream, based on the changes in land cover/climate/etc present in the scenario, which provides a way of evaluating impacts to downstream uses such as reservoirs and drinking water._"

I was specifically referring to the definitions in `ARG_SPECS`, such as for Threshold Flow Accumulation. But either way, a sweeping replacement of these terms would still make the UG more accurate than before.

2022-03-02 00:21 UTC, emlys commented
thanks @jagoldstein! I did not make any changes to the user's guide content yet. I meant to ask if you would like to make those UG edits since you're familiar with the appropriate contexts for using "slope" vs "stream"? All the changes I made here in the code & comments seem pretty clearly a "slope" context.

2022-03-02 00:38 UTC, jagoldstein commented
no problem @emlys! I will take care of those terms in the body of the UG (which are NOT pulled from `ARG_SPECS`)

2022-03-03 13:29 UTC, davemfish requested changes
Looks good! I noticed one missing word in a docstring we might as well fix now. And the UG builds aren't building because of arg key changes I think. Do we need a change on the UG side?

2022-03-03 13:29 UTC, davemfish commented on src/natcap/invest/delineateit/delineateit.py
> +        args['flow_threshold'] (int):  The number of upslope cells that must
Reading this sentence, there's a word missing: "flow"?

2022-03-03 13:30 UTC, davemfish commented
Oops, this is still in Draft, sorry! Feel free to ask me to review again when you're ready.

2022-03-04 22:47 UTC, emlys commented
@davemfish this is ready now! I added that missing word and updated the user's guide.

2022-03-07 18:53 UTC, davemfish approved these changes

2022-03-07 18:54 UTC, merged