Allow error in create-dmg
natcap/invest pull request #985
Opened 2022-05-11 17:28 UTC by davemfish

There's consistently an error from `create-dmg` when it tries to unmount a volume. Until that's fixed upstream, we can make sure our workflows continue past this step.

Fixes #984 

## Checklist
- [ ] Updated HISTORY.rst (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the affected models' UIs (if relevant)

2022-05-11 19:33 UTC, emlys commented
@davemfish this is great. I wonder if we might also add a shorter timeout to the dmg building step? Looks like it took over 30 minutes, I assume most of that is waiting for the detach which is going to fail anyway.

2022-05-11 19:51 UTC, davemfish commented
> @davemfish this is great. I wonder if we might also add a shorter timeout to the dmg building step? Looks like it took over 30 minutes, I assume most of that is waiting for the detach which is going to fail anyway.

Great idea! Looking back at past builds, I saw some taking ~10 minutes. So I set the timeout for `make binaries` at 15.

2022-05-11 21:49 UTC, emlys commented on .github/workflows/build-and-test.yml
> +        timeout-minutes: 15
```suggestion
        timeout-minutes: 15
        continue-on-error: true
```

2022-05-11 21:49 UTC, emlys requested changes
Ah I guess the timeout causes it to fail at the workflow level, maybe `continue-on-error` will fix it?

2022-05-11 22:55 UTC, davemfish commented
> Ah I guess the timeout causes it to fail at the workflow level, maybe `continue-on-error` will fix it?

Ah thanks for noticing that. I added `continue-on-error` and removed the Makefile changes so we're only addressing this in one place. Presumably we'll always timeout now before `create-dmg` raises the error anyway.

2022-05-11 23:49 UTC, davemfish commented
Woah 30 mins to restore the node modules cache for Mac, 30 seconds for Windows!

2022-05-12 17:33 UTC, emlys approved these changes

2022-05-12 17:34 UTC, merged